### ISSUE TITLE
how to apply theme ?

### ISSUE THREAD

**Issue by leizard** [JSSolutions/meteor-jstree#1]
Hi, thank you for your plugin. How could I apply theme ? I add theme option like your example

```
      themes: {
        name: 'default-dark',
        dots: true,
        icons: true
      }
```

 but this didn't work ? Should I download theme and put them somewhere ?

**Comment by eterey** [comment]
You should install package with this theme:

```
meteor add jss:jstree-dark-theme
```

**Comment by leizard** [comment]
thank you for your reply ? Do you mean I should add one more theme package with

```
meteor add jss:jstree-dark-theme
```

after I add the jss package

```
meteor add jss:jstree
```

or I just have to add one package jss:jstree-dark-theme

**Comment by eterey** [comment]
You should add both of them.
Here is an example: https://github.com/JSSolutions/meteor-jstree-demo/blob/master/app/.meteor/packages

**Comment by leizard** [comment]
thank you very much!

**Comment by eterey** [comment]
No problems.
